title: File as part of entity

options:
  changeName: true
  delete: true
  replace: true
  update: true

sections:

  help:
    type: info
    headline: Help
    theme: white
    text: |
      This file is a direct upload to: **{{ file.parent.id }}**
      Permanent URL: {{ file.permalink }}

  fields:
    fields:

      description:
        extends: fields/description
        label: File caption

      source:
        type: text
        label: File credits (source, copyright, author)

      link:
        extends: fields/url
        label: Link to external Website