# https://getkirby.com/docs/guide/blueprints/tabs

label: Meta
icon: dots

columns:

  meta_column_top:
    fields:

      signature:
        extends: fields/service/signature

  meta_column_left:
    width: 1/2
    sections:

      meta_section_fields1:
        type: fields
        fields:

          category:
            extends: fields/category

          duration: false

          credits:
            extends: fields/credits

          sources:
            extends: fields/sources

          research_methods: fields/research_methods

          tags: fields/tags

          worlditem:
            extends: liebling-house/fields/worlditem

  meta_column_right:
    width: 1/2
    sections:

      meta_section_fields3:
        type: fields
        fields:

          date_created:
            extends: fields/service/modified
            label: Dataset created

          date_modified:
            extends: fields/service/modified
            label: Dataset modified

          user_created:
            extends: fields/user
            label: Created by
            width: 1/2

          user_modified:
            extends: fields/user
            label: Last modified by
            width: 1/2
