label: Meta
icon: dots

columns:

  meta_column_top:
    fields:

      signature:
        extends: fields/service/signature

  meta_column_left:
    width: 1/2
    sections:

      meta_section_fields1:
        type: fields
        fields:

          category:
            extends: fields/category

          duration: false

          credits:
            extends: fields/credits

          sources: fields/sources

          research_methods: fields/research_methods

          tags: fields/tags

          password: fields/new/password

          worlditem:
            extends: liebling-house/fields/worlditem

  meta_column_right:
    width: 1/2
    sections:

      meta_section_fields3:
        type: fields
        fields:

          date_modified: fields/service/dateModified
