label: Settings
icon: cog
columns:

  - width: 1/1
    sections:

      wiki: sections/service/wiki

  - width: 1/1
    fields:

      highlights:
        type: entities
        label: Featured on homepage
        query: page.children.listed
        info: "{{ page.count }} connections"
        image:
          cover: true
          back: '#f9f9f9'

  - width: 1/2
    fields:

      type_categories:
        type: structure
        label: Sub categories inside {{ page.title }}
        fields:
          title:
            type: text
            label: Category
  
  - width: 1/2
    fields:

      credit_roles:
        type: structure
        label: Credit roles for {{ page.title }}
        fields:
          title:
            type: text
            label: Role
            help: Use "Photography" rather than "Photographer"