title: Default

options:
  # valid for all users
  preview: true
  read:	true
  update: true
  # only allow some users
  changeTemplate:
    *: false
    admin: true
  changeSlug:
    *: false
    admin: true
  changeStatus:
    *: true
    admin: true
  changeTitle:
    *: false
    admin: true
  delete:
    *: false
    admin: true

tabs:

  tab_info:
    extends: tabs/info
    columns:
      column_left:
        sections:

          info_section_fields1: false

      column_right:
        sections:

          info_section_fields3:
            fields:

              body: fields/body

              properties: false
  
  tab_meta:
    extends: tabs/meta
    columns:
      meta_column_left:
        sections:
          meta_section_fields1:
            fields:

              category: false
              credits: false