title: Default

options:
  # valid for all users
  preview: true
  read:	true
  duplicate: false
  changeStatus: false
  changeTemplate: false
  delete: false
  # only allow some users
  update:
    *: false
    admin: true
  changeSlug:
    *: false
    admin: true
  changeTitle:
    *: false
    admin: true

columns:

  column_left:
    width: 2/3
    sections:

      left_fields:
        type: fields
        fields:

          text:
            extends: fields/body
            label: Content
            help: false

  column_right:
    width: 1/3
    sections:

      section_pages:
        extends: sections/pages
        headline: Subpages
        image:
          back: black
      
      section_uploads:
        extends: sections/files_upload
        image:
          back: black