title: Site

tabs:

  tab1:
    label: Website
    icon: globe
    columns:

      column_left:
        width: 1/2
        sections:

          section_collections:
            extends: sections/pages
            headline: Projects (Collections)
            text: "{{ page.title }}"
            image:
              query: false
              back: white
            sortable: true
            templates:
              - collection
              - collection_liebling-house

      column_right:
        width: 1/2
        sections:

          section_archive:
            extends: sections/pages
            headline: Archive
            create: false
            text: "{{ page.title }}"
            status: listed
            image:
              query: false
              back: white
            sortable: false
            templates:
              - archive

          section_pages:
            extends: sections/pages
            headline: Other pages
            templates:
              - default
              - about
              - imprint
            create:
              - default

  recent: tabs/recent

  info:
    label: Info
    icon: info

    columns:

      - width: 1/2  
        fields:

          description:
            extends: fields/description
            label: Meta description
            help: false

          tags:
            extends: fields/tags
            label: Meta keywords
            help: false

          email:
            label: Contact Email
            type: email

          issn:
            type: text
            label: Publication ID (ISSN)
            icon: book

          links:
            extends: fields/new/urls
            label: Social Media Links

      - width: 1/4
        sections:

          seo_fields:
            type: fields
            fields:

              thumbnail:
                type: files
                label: OG Image
                multiple: false

              supporters:
                type: files
                label: Supporter Logos
                help: SVG, white fill, transparent background
                query: page.images.filterBy('extension','svg')
                translate: false
                image:
                  back: black
              
          uploads:
            type: files
            
      - width: 1/4
        fields:

          team:
            type: users
            label: Team
            help: Team members have to be created first
            translate: false

  tab3: tabs/help
