title: Site

tabs:

  tab1:
    label: Website
    icon: globe
    columns:

      column_left:
        width: 1/2
        sections:

          section_collections:
            extends: sections/pages
            headline: Projects (Collections)
            text: "{{ page.title }}"
            image:
              query: false
              back: white
            sortable: true
            templates:
              - collection
              - collection_liebling-house

      column_right:
        width: 1/2
        sections:

          section_archive:
            extends: sections/pages
            headline: Archive
            create: false
            text: "{{ page.title }}"
            status: listed
            image:
              query: false
              back: white
            sortable: false
            templates:
              - archive

          section_pages:
            extends: sections/pages
            headline: Other pages
            templates:
              - default
              - about
              - imprint
            create:
              - default

  recent:
    label: Recent edits
    icon: users
    sections:

      recent:
        type: pagesdisplay
        headline: Recent edits
        query: site.archive.recentActivity.limit(20)
        layout: table
        image:
          query: page.thumbnail
          cover: true
        columns:
          text:
            label: Title
            width: 1/2
            value: "<a href="{{ page.panel.url }}">{{ page.title }}</a>"
            type: html
          type:
            label: Type
            width: 1/6
            value: "{{ page.type }}"
            mobile: false
          date_modified:
            label: Date
            width: 1/6
          user_modified:
            label: Editor
            value: "{{ page.user_modified.toUser }}"
            width: 1/6

  tab3: tabs/help
